
import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Camera, History, TrendingUp, ShieldCheck, ChevronRight, X, FileText } from 'lucide-react';
import { AnalysisResult } from '../types';

interface DashboardProps {
  history: { image: string, result: AnalysisResult, date: number }[];
  onStart: () => void;
  onViewHistory: (h: { image: string, result: AnalysisResult, date: number }) => void;
}

export default function Dashboard({ history, onStart, onViewHistory }: DashboardProps) {
  const [showTerms, setShowTerms] = useState(false);

  return (
    <div className="px-6 py-10 flex flex-col gap-10 relative">
      {/* Terms Button */}
      <div className="absolute top-4 right-6 z-20">
        <button 
          onClick={() => setShowTerms(true)}
          className="p-2 border border-[#2A2A2A] rounded-full hover:bg-white/5 text-[#555] transition-colors"
        >
          <FileText className="w-4 h-4" />
        </button>
      </div>

      {/* Hero Welcome */}
      <section>
        <h2 className="text-5xl font-serif font-medium text-[#E0D8D0] italic leading-[0.9] tracking-tighter mb-4">
          Discover <br/>
          <span className="text-[#8E9299]">Your Essence.</span>
        </h2>
        <div className="flex gap-4 items-center">
          <div className="h-[1px] flex-1 bg-[#2A2A2A]"></div>
          <p className="font-mono text-[9px] uppercase tracking-widest text-[#555]">V.1.04 Scan Active</p>
        </div>
      </section>

      {/* Terms Modal */}
      <AnimatePresence>
        {showTerms && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/90 backdrop-blur-md"
          >
            <motion.div 
              initial={{ scale: 0.95, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.95, y: 20 }}
              className="editorial-glass max-w-sm w-full p-8 relative"
            >
              <button 
                onClick={() => setShowTerms(false)}
                className="absolute top-4 right-4 text-[#555] hover:text-white"
              >
                <X className="w-5 h-5" />
              </button>

              <h3 className="text-xl font-serif italic text-white mb-6 pt-2">Legal Disclaimer & Protocol</h3>
              
              <div className="space-y-6 font-mono text-[10px] text-[#A0A0A0] uppercase tracking-wider leading-relaxed">
                <p>
                  [01] The analysis provided by FaceFlow AI is strictly heuristic and descriptive. This is not medical, professional, or cosmetic advice.
                </p>
                <p>
                  [02] The results are generated by artificial intelligence and are inherently subjective. Individual variance and environmental lighting impact accuracy.
                </p>
                <p>
                  [03] The developers and the associated company hold no legal liability for any actions taken or psychological distress resulting from the interpretation of these scores.
                </p>
                <p>
                  [04] All visual assets are processed locally and cached within the user's secure hardware environment.
                </p>
              </div>

              <button 
                onClick={() => setShowTerms(false)}
                className="w-full mt-8 py-4 bg-white text-black font-bold uppercase tracking-[0.3em] text-[10px]"
              >
                Acknowledge
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Action Call */}
      <button 
        onClick={onStart}
        className="relative group active:scale-[0.98] transition-all text-left"
      >
        <div className="editorial-glass p-8 relative z-10 hover:border-white/30 transition-colors">
          <div className="flex justify-between items-start mb-12">
             <div className="w-10 h-10 border border-[#2A2A2A] rounded-full flex items-center justify-center">
               <Camera className="w-4 h-4 text-[#8E9299]" />
             </div>
             <span className="font-mono text-[10px] uppercase tracking-widest text-white px-2 py-1 bg-white/5">01</span>
          </div>
          <h3 className="text-2xl font-serif italic text-white mb-1">New Acquisition</h3>
          <p className="font-mono text-[9px] text-[#8E9299] uppercase tracking-widest leading-loose">Begin facial resonance scan</p>
        </div>
        {/* Subtle decorative border */}
        <div className="absolute inset-0 border border-[#2A2A2A] translate-x-2 translate-y-2 -z-10 group-hover:translate-x-1 group-hover:translate-y-1 transition-transform"></div>
      </button>

      {/* Stats/Highlight Row */}
      <div className="grid grid-cols-2 gap-4">
        <div className="p-4 editorial-glass flex flex-col gap-3">
          <TrendingUp className="w-4 h-4 text-cyan-400 opacity-50" />
          <div className="font-mono text-[9px] uppercase tracking-widest text-[#8E9299]">Potential Tracking</div>
        </div>
        <div className="p-4 editorial-glass flex flex-col gap-3">
          <ShieldCheck className="w-4 h-4 text-amber-400 opacity-50" />
          <div className="font-mono text-[9px] uppercase tracking-widest text-[#8E9299]">Secured Cache</div>
        </div>
      </div>

      {/* History */}
      <section>
        <div className="flex items-center justify-between mb-6 pb-2 border-b border-[#2A2A2A]">
          <h3 className="font-mono text-[10px] uppercase font-bold tracking-widest text-white flex items-center gap-2">
             Recent Logs
          </h3>
          <span className="font-mono text-[8px] text-[#555] uppercase tracking-widest italic">{history.length} Entries</span>
        </div>

        {history.length === 0 ? (
          <div className="py-16 editorial-glass border-dashed flex flex-col items-center justify-center text-center opacity-30">
            <History className="w-8 h-8 mb-4 stroke-1" />
            <p className="font-mono text-[9px] uppercase tracking-widest">Logs Empty</p>
          </div>
        ) : (
          <div className="flex flex-col gap-3">
            {history.map((item, idx) => (
              <button 
                key={idx} 
                onClick={() => onViewHistory(item)}
                className="w-full p-4 editorial-glass hover:bg-white/[0.03] transition-colors flex items-center gap-4 text-left group"
              >
                <div className="w-12 h-12 rounded-none bg-zinc-900 border border-[#2A2A2A] grayscale brightness-75 group-hover:grayscale-0 group-hover:brightness-100 transition-all overflow-hidden flex-shrink-0">
                  <img src={item.image} alt="Scan" className="w-full h-full object-cover" />
                </div>
                <div className="flex-1">
                  <div className="flex items-center justify-between font-mono">
                    <span className="text-[10px] text-white">SCORE: {item.result.scores.overall.toFixed(1)}</span>
                    <span className="text-[8px] text-[#555]">{new Date(item.date).toLocaleDateString([], { month: 'short', day: 'numeric' })}</span>
                  </div>
                  <p className="text-[10px] text-[#8E9299] italic line-clamp-1 mt-1">"{item.result.summary}"</p>
                </div>
                <ChevronRight className="w-3 h-3 text-[#555] group-hover:text-white transition-colors" />
              </button>
            ))}
          </div>
        )}
      </section>

      {/* Footer Info */}
      <div className="mt-4 pt-4 border-t border-[#2A2A2A] flex justify-between items-center opacity-40">
        <p className="text-[8px] font-mono uppercase tracking-tighter max-w-[200px] leading-relaxed">
          Subjective analysis — V.1.04. Aura Encryption Active.
        </p>
        <span className="font-mono text-[8px] tracking-widest">482-X9L</span>
      </div>
    </div>
  );
}
